"""Topic blocks for Django chapters 5-14."""
from django_topics import block

CH5 = {
"t1": block("Template System Overview", "> **Definition:** Templates separate presentation from Python logic.\n\nDjango Template Language avoids arbitrary Python in HTML for security. Views call `render(request, template, context)`."),
"t2": block("Template Layout and Namespaces", "```text\nblog/templates/blog/post_list.html\n```\n\nApp name subfolder prevents template name collisions."),
"t3": block("Syntax: Variables Tags Comments", "```django\n{{ post.title }}\n{% if user.is_authenticated %}{% endif %}\n{# comment #}\n```"),
"t4": block("Inheritance and Blocks", "```django\n{% extends \"blog/base.html\" %}\n{% block content %}...{% endblock %}\n```"),
"t5": block("Loops and Conditionals", "```django\n{% for post in posts %}{{ forloop.counter }}{% empty %}No posts{% endfor %}\n```"),
"t6": block("url and static Tags", "```django\n{% url 'post-detail' pk=post.pk %}\n{% load static %}\n<link href=\"{% static 'css/style.css' %}\">\n```"),
"t7": block("Filters Reference", "| Filter | Use |\n|--------|-----|\n| date | Format datetime |\n| default | Fallback |\n| truncatewords | Shorten text |"),
"t8": block("Context and Processors", "Context processors inject `user`, `request`, `messages` globally."),
"t9": block("Custom Tags and Filters", "Create `templatetags/` module with `@register.filter`."),
"t10": block("CSRF in Forms", "`{% csrf_token %}` required on POST forms."),
"t11": block("XSS and Escaping", "Auto-escape in `{{ }}`. Never `|safe` on user content."),
"t12": block("Debugging Templates", "Read TemplateDoesNotExist searched paths list."),
"t13": block("Including Partials", "```django\n{% include \"blog/partials/pagination.html\" %}\n```\n\nPass context with `with`:`{% include \"x\" with foo=bar %}`."),
"t14": block("Template Loaders", "Filesystem and app_directories loaders search DIRS then each app's templates/."),
"t15": block("Built-in Template Reference", "Bookmark Django docs: Built-in template tags and filters. Learn `widthratio`, `yesno`, `pluralize` when needed."),
}

CH6 = {
"t1": block("Why Forms", "Forms validate input and render HTML consistently."),
"t2": block("Form Class", "```python\nclass ContactForm(forms.Form):\n    email = forms.EmailField()\n```"),
"t3": block("Validation", "`is_valid()`, `cleaned_data`, `clean_<field>`, `clean()`."),
"t4": block("Views with Forms", "GET empty form; POST bound form; redirect on success."),
"t5": block("Template Rendering", "`as_p`, manual loop, field.errors."),
"t6": block("ModelForm", "`class Meta: model = Post; fields = [...]`"),
"t7": block("CSRF", "Middleware + `{% csrf_token %}` + AJAX header."),
"t8": block("Widgets", "attrs for CSS classes on widgets."),
"t9": block("Errors", "field.errors and non_field_errors."),
"t10": block("Formsets", "modelformset_factory for multiple rows."),
"t11": block("File Uploads", "multipart enctype and request.FILES."),
"t12": block("Security", "Only expose intended fields in ModelForm Meta.fields."),
"t13": block("Field Types Reference", "| Field | Input |\n|-------|-------|\n| CharField | text |\n| EmailField | email |\n| ChoiceField | select |\n| BooleanField | checkbox |"),
"t14": block("ModelForm Meta exclude", "Prefer explicit `fields` over broad `exclude` — prevents mass-assignment of sensitive columns."),
"t15": block("Displaying Validation Errors", "Loop `field.errors` in template; show `form.non_field_errors` for `clean()` failures."),
}

CH7 = {
"t1": block("Admin Overview", "Auto CRUD at /admin/ for staff users."),
"t2": block("register and ModelAdmin", "@admin.register(Post) class PostAdmin(admin.ModelAdmin)"),
"t3": block("list_display", "Columns on changelist page."),
"t4": block("list_filter and search", "Sidebar filters and search box."),
"t5": block("fieldsets", "Group fields on change form."),
"t6": block("inlines", "TabularInline / StackedInline for related models."),
"t7": block("actions", "@admin.action bulk operations."),
"t8": block("permissions", "has_*_permission overrides."),
"t9": block("display methods", "@admin.display custom columns."),
"t10": block("queryset", "get_queryset limits rows per user."),
"t11": block("branding", "site_header, site_title customization."),
"t12": block("admin vs custom UI", "Admin for internal; public site uses views."),
"t13": block("prepopulated_fields", "`prepopulated_fields = {'slug': ('title',)}` auto-fills slug while typing in admin."),
"t14": block("readonly_fields", "Show timestamps without allowing edits: `readonly_fields = ['created_at']`."),
"t15": block("list_editable", "Edit columns directly on changelist: `list_editable = ['published']` — use carefully."),
}

CH8 = {
"t1": block("Auth Overview", "django.contrib.auth: users, groups, permissions."),
"t2": block("User model", "create_user, create_superuser, set_password."),
"t3": block("Login Logout", "LoginView, LogoutView, LOGIN_URL settings."),
"t4": block("Decorators", "@login_required, @permission_required."),
"t5": block("Templates user", "{% if user.is_authenticated %}"),
"t6": block("Groups", "Group permissions assigned to users."),
"t7": block("AUTH_USER_MODEL", "FK to settings.AUTH_USER_MODEL always."),
"t8": block("Custom User", "AbstractUser before first migrate."),
"t9": block("Password validators", "AUTH_PASSWORD_VALIDATORS list."),
"t10": block("Sessions", "SESSION_COOKIE_SECURE in production."),
"t11": block("Permissions on models", "add, change, delete, view per model."),
"t12": block("Object-level permissions", "Third-party or custom checks in views."),
"t13": block("Password hashing", "Django stores hashed passwords — never plain text. `user.check_password('x')`."),
"t14": block("Login required redirect", "`LOGIN_URL` setting where anonymous users go for @login_required."),
"t15": block("UserPassesTestMixin", "CBV: override `test_func()` for custom authorization logic."),
}

CH9 = {
"t1": block("Migrations Intro", "Python files tracking schema versions."),
"t2": block("makemigrations migrate", "Create files then apply to database."),
"t3": block("showmigrations sqlmigrate", "Status and SQL preview."),
"t4": block("Migration structure", "dependencies and operations list."),
"t5": block("AddField nullable", "Multi-step for non-null on existing data."),
"t6": block("RunPython", "Data migrations with apps.get_model."),
"t7": block("squashmigrations", "Combine migration history."),
"t8": block("fake rollback", "--fake and migrate to older number."),
"t9": block("best practices", "Commit migrations; never edit applied."),
"t10": block("conflicts", "Merge migration files when teams diverge."),
"t11": block("zero downtime", "Nullable first, backfill, enforce constraint."),
"t12": block("testing migrations", "Test on copy of production data."),
"t13": block("RenameField RenameModel", "Use migration operations instead of manual SQL when renaming."),
"t14": block("RunSQL", "Escape hatch for raw SQL in migrations — use rarely with reviewed SQL."),
"t15": block("Migration plan command", "`sqlmigrate app 0001` previews SQL before applying."),
}

CH10 = {
"t1": block("Static vs Media", "Static from repo; media from users."),
"t2": block("STATIC settings", "STATIC_URL, STATICFILES_DIRS, STATIC_ROOT."),
"t3": block("static tag", "{% load static %}{% static 'path' %}"),
"t4": block("collectstatic", "Gather files for production."),
"t5": block("MEDIA settings", "MEDIA_URL, MEDIA_ROOT."),
"t6": block("FileField", "upload_to path on model."),
"t7": block("dev serving", "static() in urls when DEBUG."),
"t8": block("production", "nginx or S3, not Django for scale."),
"t9": block("Whitenoise", "Middleware for static on PaaS."),
"t10": block("storages S3", "django-storages backend."),
"t11": block("findstatic", "Debug path resolution."),
"t12": block("cache busting", "ManifestStaticFilesStorage hashed names."),
"t13": block("STATICFILES_FINDERS", "FileSystemFinder + AppDirectoriesFinder locate static files."),
"t14": block("ImageField Pillow", "pip install Pillow for ImageField support."),
"t15": block("Private media", "Do not expose private uploads under public MEDIA_URL; use signed URLs."),
}

CH11 = {
"t1": block("CBV Intro", "Classes map HTTP methods to methods."),
"t2": block("View base", "class MyView(View): def get(self, request)"),
"t3": block("ListView", "model, queryset, paginate_by."),
"t4": block("DetailView", "Single object by pk or slug."),
"t5": block("CreateView UpdateView", "ModelForm integration."),
"t6": block("DeleteView", "Confirmation template on POST."),
"t7": block("as_view urls", "PostListView.as_view() in urlpatterns."),
"t8": block("Mixins", "LoginRequiredMixin, UserPassesTestMixin."),
"t9": block("form_valid", "Set author before save."),
"t10": block("method flow", "dispatch -> get -> get_queryset -> render."),
"t11": block("FBV vs CBV", "FBV flexible; CBV DRY for CRUD."),
"t12": block("Template names", "app/model_list.html convention."),
"t13": block("get_success_url", "Override `get_success_url()` for dynamic redirect after create/update."),
"t14": block("context_object_name", "Rename default `object_list` to `posts` in templates."),
"t15": block("MultipleObjectMixin", "Understand queryset = model.objects.all() default in ListView."),
}

CH12 = {
"t1": block("Dev vs Prod", "DEBUG, server, DB, static differ."),
"t2": block("prod settings", "DEBUG=False, ALLOWED_HOSTS, env secrets."),
"t3": block("Gunicorn", "gunicorn mysite.wsgi:application"),
"t4": block("nginx stack", "SSL, static, proxy to Gunicorn."),
"t5": block("deploy checklist", "install migrate collectstatic run."),
"t6": block("environ", "django-environ for env vars."),
"t7": block("logging", "LOGGING to stdout for containers."),
"t8": block("hosting", "Railway Render Fly AWS VPS."),
"t9": block("health check", "Simple 200 OK endpoint."),
"t10": block("docker", "Optional Dockerfile CMD gunicorn."),
"t11": block("postgres", "Production database choice."),
"t12": block("HTTPS cookies", "SECURE_SSL_REDIRECT, secure cookies."),
"t13": block("ALLOWED_HOSTS", "Required when DEBUG=False — list domain names."),
"t14": block("Database connection pooling", "CONN_MAX_AGE in DATABASES for persistent connections."),
"t15": block("Static on CDN", "Point STATIC_URL to CDN after collectstatic upload."),
}

CH13 = {
"t1": block("Project layout", "config/, apps/, split settings."),
"t2": block("fat models", "Business logic on models/services."),
"t3": block("ORM perf", "select_related, prefetch_related."),
"t4": block("security", "CSRF XSS SQL injection mitigation."),
"t5": block("indexes", "db_index on filtered columns."),
"t6": block("testing", "TestCase and Client."),
"t7": block("URLs", "Named URLs and namespaces."),
"t8": block("settings antipatterns", "No DEBUG in prod."),
"t9": block("PEP8", "Follow Python style guide."),
"t10": block("requirements", "Pin versions in requirements.txt."),
"t11": block("debug toolbar", "Development query analysis."),
"t12": block("documentation", "README setup instructions."),
"t13": block("Service layer", "Optional services.py for complex workflows instead of fat views."),
"t14": block("Database transactions", "atomic() for operations that must succeed or fail together."),
"t15": block("Pagination", "Use Paginator or ListView paginate_by for large lists."),
}

CH14 = {
"t1": block("Interview roadmap", "Map topics to chapters 1-13."),
"t2": block("MTV questions", "Explain model template view roles."),
"t3": block("request cycle", "Middleware URL view template response."),
"t4": block("ORM questions", "N+1, select_related, prefetch, F, Q."),
"t5": block("null blank", "DB vs validation; strings use blank."),
"t6": block("CSRF SQL XSS", "How Django mitigates each."),
"t7": block("middleware order", "Session before auth."),
"t8": block("caching", "cache_page and Redis backend."),
"t9": block("signals", "post_save; use sparingly."),
"t10": block("system design", "Blog auth uploads scale Celery."),
"t11": block("coding drills", "JSON without N+1, slug URL, author edit."),
"t12": block("resources", "Official docs and practice project."),
"t13": block("ORM get vs filter", "get() exact match one row; filter() returns QuerySet."),
"t14": block("Django cache framework", "Per-site cache, per-view, template fragment caching."),
"t15": block("Explain tradeoffs aloud", "Practice explaining FBV vs CBV and monolith vs API for interviews."),
}

CHAPTER_TOPICS_EXTRA = {
    5: (CH5, list(CH5.keys())),
    6: (CH6, list(CH6.keys())),
    7: (CH7, list(CH7.keys())),
    8: (CH8, list(CH8.keys())),
    9: (CH9, list(CH9.keys())),
    10: (CH10, list(CH10.keys())),
    11: (CH11, list(CH11.keys())),
    12: (CH12, list(CH12.keys())),
    13: (CH13, list(CH13.keys())),
    14: (CH14, list(CH14.keys())),
}
