# Topic blocks for Django chapter generator (~50+ lines each)
from __future__ import annotations

def block(title: str, body: str) -> str:
    enrich = f"""
### Why this matters

Understanding **{title}** helps you build maintainable Django projects and answer common interview questions. Connect this section to the MTV flow: identify which models, views, and templates are involved.

### Try it yourself

1. Open your practice project and locate the files mentioned above.
2. Type the code examples manually — do not copy-paste without reading.
3. Change one line intentionally to cause an error, then read the traceback.
4. Run `python manage.py check` and `python manage.py test` after changes.

### Check your understanding

- Can you explain **{title}** in one sentence?
- What breaks if you skip or misconfigure this?
- Which official Django documentation page covers this topic?

"""
    return f"## {title}\n\n{body.strip()}\n{enrich}\n---\n\n"


# ---------- Chapter 2 topics ----------
CH2 = {
"install": block("Installation and Virtual Environments", """
> **Definition:** A **virtual environment** is an isolated Python environment for one project. Django and its dependencies install there without conflicting with other projects.

You learned virtual environments in the CodeShelf Python course. Django projects **always** use one.

### Windows (PowerShell)

```bash
cd D:\\projects\\myblog
python -m venv .venv
.venv\\Scripts\\Activate.ps1
python -m pip install --upgrade pip
pip install "django>=5.0,<6.0"
python -m django --version
```

### macOS / Linux

```bash
cd ~/projects/myblog
python3 -m venv .venv
source .venv/bin/activate
pip install "django>=5.0,<6.0"
django-admin --version
```

### requirements.txt

```text
django>=5.0,<6.0
```

Commit `requirements.txt` to git. Teammates run `pip install -r requirements.txt` for identical versions.

| Check | Command |
|-------|---------|
| Python version | `python --version` (3.10+ recommended) |
| Django installed | `python -m django --version` |
| Pip list | `pip list` |
"""),
"startproject": block("Creating Your First Project", """
`django-admin` is Django's command-line utility for administrative tasks.

```bash
django-admin startproject mysite
cd mysite
```

### What `startproject` creates

```text
mysite/
├── manage.py
└── mysite/
    ├── __init__.py
    ├── settings.py
    ├── urls.py
    ├── asgi.py
    └── wsgi.py
```

| File | Purpose |
|------|---------|
| `manage.py` | CLI entry: runserver, migrate, shell, test |
| `settings.py` | Database, installed apps, middleware, templates |
| `urls.py` | Root URL routing |
| `wsgi.py` | Production server entry point |
| `asgi.py` | Async / Channels entry point |

### First run

```bash
python manage.py runserver
```

Open `http://127.0.0.1:8000/` — you should see the Django welcome rocket page.

```bash
python manage.py runserver 8080
```

Runs on port 8080 instead of 8000.
"""),
"manage_py": block("Understanding manage.py", """
`manage.py` sets `DJANGO_SETTINGS_MODULE` and delegates to Django's command runner.

```python
# manage.py (simplified idea)
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mysite.settings")
execute_from_command_line(sys.argv)
```

### Essential commands (learn these first)

| Command | What it does |
|---------|----------------|
| `runserver` | Development HTTP server (never for production) |
| `migrate` | Apply database migrations |
| `makemigrations` | Create migration files from model changes |
| `createsuperuser` | Create admin login |
| `shell` | Python REPL with Django loaded |
| `test` | Run test suite |
| `startapp NAME` | Create a new app |
| `collectstatic` | Gather static files for production |

### Example workflow

```bash
python manage.py startapp blog
# edit models.py
python manage.py makemigrations blog
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
```
"""),
"startapp": block("Creating and Registering Apps", """
```bash
python manage.py startapp blog
```

```text
blog/
├── __init__.py
├── admin.py
├── apps.py
├── migrations/
│   └── __init__.py
├── models.py
├── tests.py
└── views.py
```

Create `blog/urls.py` yourself (not generated by default):

```python
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="blog-index"),
]
```

Register in `settings.py`:

```python
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "blog",
]
```

> **Rule:** If the app is not in `INSTALLED_APPS`, Django ignores its models, templates, and static files.
"""),
"settings": block("settings.py Deep Dive", """
`settings.py` is the control center of your project.

### Critical settings

```python
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-change-me"  # use env var in production
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [...]
MIDDLEWARE = [...]
ROOT_URLCONF = "mysite.urls"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
```

| Setting | Development | Production |
|---------|-------------|------------|
| `DEBUG` | `True` | **`False`** |
| `ALLOWED_HOSTS` | `[]` ok locally | `["yourdomain.com"]` |
| `SECRET_KEY` | dev key | long random env var |
| `DATABASES` | SQLite fine | PostgreSQL typical |

### TEMPLATES and static (preview)

```python
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {"context_processors": [...]},
    },
]

STATIC_URL = "static/"
```

Full template/static chapters: [ch05](./ch05-templates.md), [ch10](./ch10-static-media-files.md).
"""),
"urls": block("Wiring URLs: Project and App", """
```python
# mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
]
```

```python
# blog/views.py
from django.http import HttpResponse

def index(request):
    return HttpResponse("<h1>Blog home</h1>")
```

Visit `http://127.0.0.1:8000/blog/` — not `/` unless you add a root route.

### Named URLs

```python
path("", views.index, name="blog-index"),
```

Use `reverse("blog-index")` in Python and `{% url 'blog-index' %}` in templates later.
"""),
"migrate": block("First Migration and Database", """
```bash
python manage.py migrate
```

Creates tables for built-in apps: auth, admin, sessions, contenttypes.

```bash
python manage.py showmigrations
```

`[X]` means applied; `[ ]` means pending.

### SQLite file

After migrate, `db.sqlite3` appears in the project root. It is your database file in development.

> **Production:** Use PostgreSQL or MySQL — not SQLite for concurrent write-heavy sites.
"""),
"superuser": block("Superuser and Admin Preview", """
```bash
python manage.py createsuperuser
```

Follow prompts for username, email, password.

```bash
python manage.py runserver
```

Visit `http://127.0.0.1:8000/admin/` and log in.

Full admin customization: [Chapter 7](./ch07-admin-panel.md).
"""),
"layout": block("Recommended Project Layout", """
Small tutorials use flat layout. Real projects often grow:

```text
myproject/
├── config/
│   ├── settings/
│   │   ├── base.py
│   │   ├── dev.py
│   │   └── prod.py
│   ├── urls.py
│   └── wsgi.py
├── apps/
│   ├── blog/
│   └── accounts/
├── templates/
├── static/
├── media/
├── manage.py
└── requirements.txt
```

| Pattern | Benefit |
|---------|---------|
| `config/` instead of duplicate name | Clear separation |
| Split settings | Safe production defaults |
| `apps/` folder | Many apps stay organized |

Deployment split settings: [Chapter 12](./ch12-deployment-basics.md).
"""),
"env": block("Environment Variables and Secrets", """
Never commit production secrets.

```python
import os

SECRET_KEY = os.environ.get("SECRET_KEY", "dev-only-key")
DEBUG = os.environ.get("DEBUG", "True") == "True"
```

Use `python-dotenv` or `django-environ` locally:

```text
# .env (gitignored)
SECRET_KEY=your-long-random-key
DEBUG=True
```

```python
# .gitignore
.env
db.sqlite3
__pycache__/
*.pyc
.venv/
```
"""),
"debug": block("Reading Django Error Pages", """
With `DEBUG=True`, Django shows a detailed yellow error page:

| Section | Use it to |
|---------|-----------|
| Exception type | Know error class (DoesNotExist, etc.) |
| Traceback | Find exact line in your code |
| Request info | See URL, method, POST data |
| Settings | Confirm which settings module loaded |

**In production** (`DEBUG=False`), users see a generic 500 page — you log errors server-side.

Common first errors:
- `TemplateDoesNotExist` — wrong template path
- `NoReverseMatch` — URL name typo
- `AppRegistryNotReady` — model import order issue
"""),
"checklist": block("Chapter 2 Setup Checklist", """
Before moving to models, confirm:

```text
[ ] Virtual environment active
[ ] Django installed and version printed
[ ] startproject completed
[ ] startapp blog completed
[ ] blog in INSTALLED_APPS
[ ] blog/urls.py created and included
[ ] View returns HttpResponse
[ ] migrate run successfully
[ ] createsuperuser works
[ ] /admin/ login works
```
"""),
}

CH3 = {
"orm_intro": block("What is the ORM?", """
> **Definition:** The **Object-Relational Mapper (ORM)** maps Python classes to database tables and instances to rows. You query with Python instead of writing SQL for most operations.

```python
Post.objects.filter(published=True)
```

Translates roughly to:

```sql
SELECT * FROM blog_post WHERE published = true;
```

Benefits:
- Database-agnostic code (switch SQLite to PostgreSQL with settings change)
- Protection against SQL injection when using ORM APIs
- Migrations keep schema in sync with models

Raw SQL is still available when needed: `Post.objects.raw("SELECT ...")`.
"""),
"define_model": block("Defining Your First Model", """
```python
# blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    body = models.TextField()
    published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "posts"

    def __str__(self):
        return self.title
```

| Piece | Purpose |
|-------|---------|
| `class Post(models.Model)` | Defines table `blog_post` |
| `__str__` | Human-readable in admin/shell |
| `Meta.ordering` | Default sort for QuerySets |
| `auto_now_add` | Set once on create |
| `auto_now` | Updated every save |
"""),
"fields": block("Common Field Types", """
| Field | Database | Use case |
|-------|----------|----------|
| `CharField` | VARCHAR | Titles, names (requires `max_length`) |
| `TextField` | TEXT | Long content |
| `IntegerField` | INTEGER | Counts |
| `PositiveIntegerField` | INTEGER | Views, ratings (>=0) |
| `BooleanField` | BOOLEAN | Flags |
| `DateField` | DATE | Birth dates |
| `DateTimeField` | TIMESTAMP | Created/updated |
| `EmailField` | VARCHAR | Emails (validation) |
| `URLField` | VARCHAR | URLs |
| `SlugField` | VARCHAR | URL segments |
| `DecimalField` | DECIMAL | Money (`max_digits`, `decimal_places`) |
| `JSONField` | JSON | Flexible metadata |
| `FileField` / `ImageField` | path | Uploads (needs Pillow for images) |

```python
price = models.DecimalField(max_digits=10, decimal_places=2)
metadata = models.JSONField(default=dict, blank=True)
```
"""),
"field_options": block("Field Options: null, blank, default", """
| Option | Layer | Meaning |
|--------|-------|---------|
| `null=True` | Database | Column allows NULL |
| `blank=True` | Validation | Forms may leave empty |
| `default` | Both | Value when not provided |
| `unique=True` | Database | Unique constraint |
| `db_index=True` | Database | Index for faster lookups |
| `choices` | Validation | Limited allowed values |

```python
STATUS = [("draft", "Draft"), ("published", "Published")]

status = models.CharField(max_length=20, choices=STATUS, default="draft")
```

**String fields:** prefer `blank=True` without `null=True` (Django convention: empty string, not NULL).

**Non-string optional fields:** use both `null=True, blank=True`.
"""),
"relationships": block("Relationships: ForeignKey, M2M, OneToOne", """
```python
from django.conf import settings

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="posts",
    )
    tags = models.ManyToManyField(Tag, blank=True)
```

| Type | Cardinality | Reverse accessor |
|------|-------------|------------------|
| `ForeignKey` | many-to-one | `author.posts.all()` |
| `ManyToManyField` | many-to-many | `tag.post_set.all()` |
| `OneToOneField` | one-to-one | `user.profile` |

### on_delete (required on ForeignKey)

| Value | Behavior |
|-------|----------|
| `CASCADE` | Delete children when parent deleted |
| `PROTECT` | Raise error if children exist |
| `SET_NULL` | Set FK null (needs `null=True`) |
| `SET_DEFAULT` | Set to default value |
"""),
"crud": block("CRUD with the ORM", """
### Create

```python
post = Post.objects.create(title="Hello", body="World", slug="hello")
# or
post = Post(title="Hi", body="...")
post.save()
```

### Read

```python
Post.objects.all()
Post.objects.get(pk=1)
Post.objects.filter(published=True)
Post.objects.filter(title__icontains="django")
Post.objects.exclude(published=False)
Post.objects.order_by("-created_at")[:10]
```

### Update

```python
post.title = "Updated"
post.save()
Post.objects.filter(pk=1).update(published=True)
```

### Delete

```python
post.delete()
Post.objects.filter(published=False).delete()
```

> `get()` raises `DoesNotExist` if 0 rows and `MultipleObjectsReturned` if >1. Use `filter().first()` when unsure.
"""),
"queryset": block("QuerySets and Laziness", """
> **Definition:** A **QuerySet** is a lazy collection of model instances. The database query runs when you **evaluate** the QuerySet.

Evaluation triggers:
- Iteration: `for post in posts`
- `list(posts)`, `len(posts)`
- `bool(posts)` in `if posts`
- slicing with step (sometimes)
- `print(posts.query)` after evaluation

```python
qs = Post.objects.filter(published=True)  # no SQL yet
for p in qs:  # SQL runs here
    print(p.title)
```

Chaining returns new QuerySets:

```python
Post.objects.filter(published=True).order_by("-created_at").select_related("author")
```
"""),
"lookups": block("Field Lookups", """
Double underscore: `field__lookup=value`

```python
Post.objects.filter(views__gte=100)
Post.objects.filter(title__startswith="Django")
Post.objects.filter(created_at__year=2024)
Post.objects.filter(email__isnull=True)
Post.objects.filter(status__in=["draft", "review"])
```

| Lookup | Meaning |
|--------|---------|
| `exact`, `iexact` | Equal (case sensitive / insensitive) |
| `contains`, `icontains` | Substring |
| `startswith`, `endswith` | Prefix/suffix |
| `gt`, `gte`, `lt`, `lte` | Comparisons |
| `in` | In list |
| `range` | Between |
| `isnull` | NULL check |
| `date`, `year`, `month` | Date parts |
"""),
"q_f": block("Q Objects and F Expressions", """
```python
from django.db.models import Q, F

Post.objects.filter(Q(published=True) | Q(author__username="admin"))
Post.objects.filter(Q(title__icontains="django") & Q(published=True))

Post.objects.update(views=F("views") + 1)
```

| Tool | Use |
|------|-----|
| `Q` | Complex OR/AND/NOT in filters |
| `F` | Reference column values in queries (atomic updates) |

`F` avoids race conditions:

```python
# BAD: read-modify-write race
post.views += 1
post.save()

# GOOD: database-level increment
Post.objects.filter(pk=post.pk).update(views=F("views") + 1)
```
"""),
"aggregate": block("Aggregation and Annotation", """
```python
from django.db.models import Count, Avg, Max, Min, Sum

Post.objects.aggregate(avg_views=Avg("views"), total=Count("id"))
# {'avg_views': 42.5, 'total': 100}

from django.contrib.auth import get_user_model
User = get_user_model()
User.objects.annotate(post_count=Count("posts")).filter(post_count__gt=5)
```

| Method | Returns |
|--------|---------|
| `aggregate()` | Dict of aggregates over entire queryset |
| `annotate()` | Adds aggregate per row to each instance |
"""),
"managers": block("Custom Managers", """
```python
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(published=True)

class Post(models.Model):
    # fields...
    objects = models.Manager()
    published = PublishedManager()

Post.published.all()
```

Use managers for default filtering (published only, soft-delete exclusion).
"""),
"select": block("select_related and prefetch_related", """
```python
# N+1 problem
for post in Post.objects.all():
    print(post.author.username)  # extra query per post!

# Fix FK with select_related
for post in Post.objects.select_related("author"):
    print(post.author.username)

# Fix M2M with prefetch_related
for post in Post.objects.prefetch_related("tags"):
    for tag in post.tags.all():
        print(tag.name)
```

| Method | SQL strategy | For |
|--------|--------------|-----|
| `select_related` | SQL JOIN | ForeignKey, OneToOne |
| `prefetch_related` | Separate query + join in Python | ManyToMany, reverse FK |
"""),
"meta": block("Model Meta Options", """
```python
class Meta:
    ordering = ["-created_at"]
    verbose_name = "blog post"
    verbose_name_plural = "blog posts"
    indexes = [models.Index(fields=["slug"])]
    constraints = [
        models.UniqueConstraint(fields=["author", "slug"], name="unique_author_slug")
    ]
```

| Option | Effect |
|--------|--------|
| `ordering` | Default ORDER BY |
| `indexes` | Database indexes |
| `constraints` | DB-level rules |
| `db_table` | Custom table name |
"""),
}

# Additional chapter topic dicts - CH4 through CH14
# (abbreviated keys; generator merges standard endings)

def _views_block(name: str, body: str) -> str:
    return block(name, body)

CH4_EXTRA = {
"http_methods": block("HTTP Methods Summary", """
| Method | Typical use in Django |
|--------|----------------------|
| GET | Display pages, safe reads |
| POST | Create, update via forms |
| PUT/PATCH | APIs (DRF) |
| DELETE | APIs or DeleteView POST |

Use `@require_http_methods` or `@require_GET` to restrict views.
"""),
"redirects": block("Redirects", """
```python
from django.shortcuts import redirect
return redirect("post-list")
return redirect("post-detail", pk=42)
from django.http import HttpResponseRedirect
return HttpResponseRedirect("/legacy/")
```
"""),
"class_redirect": block("Permanent vs Temporary Redirects", "`redirect()` defaults to 302. Use `redirect(..., permanent=True)` for 301 when URLs move permanently."),
}

CH4 = {
"routing": _views_block("URL Routing and URLconf", """
> **Definition:** **URLconf** is a list of URL patterns Django matches against the request path.

```python
from django.urls import path
from . import views

urlpatterns = [
    path("", views.post_list, name="post-list"),
    path("<int:pk>/", views.post_detail, name="post-detail"),
    path("create/", views.post_create, name="post-create"),
]
```

| Converter | Matches |
|-----------|---------|
| `str` | Non-empty string (no `/`) |
| `int` | Positive integers |
| `slug` | Slug characters |
| `uuid` | UUID |
| `path` | Any path including `/` |

```python
path("archive/<int:year>/", views.archive_year),
re_path(r"^legacy/(?P<id>\\d+)/$", views.legacy),
```
"""),
"fbv": _views_block("Function-Based Views", """
```python
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post

def post_list(request):
    posts = Post.objects.filter(published=True)
    return render(request, "blog/post_list.html", {"posts": posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk, published=True)
    return render(request, "blog/post_detail.html", {"post": post})
```

| Helper | Purpose |
|--------|---------|
| `render()` | Template + context -> HttpResponse |
| `get_object_or_404()` | get() or HTTP 404 |
| `redirect()` | Short redirect response |
| `reverse()` | Build URL from name |
"""),
"request": _views_block("The HttpRequest Object", """
```python
def debug_request(request):
    print(request.method)      # GET, POST, ...
    print(request.path)        # /blog/5/
    print(request.GET)         # query string
    print(request.POST)        # form body
    print(request.user)        # auth user
    print(request.session)     # session dict
    print(request.headers)     # HTTP headers
    print(request.FILES)       # uploads
```

```python
q = request.GET.get("q", "")
page = int(request.GET.get("page", 1))
```

Always validate and bound user input (max page size, sanitize search terms).
"""),
"response": _views_block("HttpResponse Types", """
```python
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound, Http404

def plain(request):
    return HttpResponse("Hello", content_type="text/plain")

def json_posts(request):
    data = list(Post.objects.values("id", "title"))
    return JsonResponse(data, safe=False)

def raise_404(request):
    raise Http404("Post not found")
```

| Class | Use |
|-------|-----|
| `HttpResponse` | Arbitrary body |
| `JsonResponse` | JSON API |
| `HttpResponseRedirect` | 302 redirect |
| `HttpResponseNotFound` | 404 without exception |
"""),
"reverse": _views_block("Named URLs and reverse()", """
```python
from django.urls import reverse
from django.shortcuts import redirect

def after_create(request, post):
    return redirect("post-detail", pk=post.pk)
    # equivalent: redirect(reverse("post-detail", kwargs={"pk": post.pk}))
```

Template:

```django
<a href="{% url 'post-detail' pk=post.pk %}">Read more</a>
```

Never hard-code `/blog/5/` in multiple files — rename URLs once via `name=`.
"""),
"include": _views_block("include() and URL Namespaces", """
```python
# project urls.py
path("blog/", include("blog.urls", namespace="blog")),

# blog/urls.py
app_name = "blog"
urlpatterns = [...]
```

```python
reverse("blog:post-detail", kwargs={"pk": 1})
```

```django
{% url 'blog:post-detail' pk=post.pk %}
```

Namespaces prevent name collisions between apps (`blog:post-list` vs `shop:post-list`).
"""),
"post": _views_block("Handling POST Requests", """
```python
from django.views.decorators.http import require_http_methods

@require_http_methods(["GET", "POST"])
def post_create(request):
    if request.method == "POST":
        title = request.POST.get("title", "").strip()
        if title:
            post = Post.objects.create(title=title, body="", slug="temp")
            return redirect("post-detail", pk=post.pk)
    return render(request, "blog/post_form.html")
```

Prefer [Django Forms](./ch06-forms.md) over raw `request.POST` for validation.
"""),
"decorators": _views_block("View Decorators", """
```python
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.http import require_GET, require_POST
from django.views.decorators.cache import cache_page

@login_required
@require_POST
def publish(request, pk):
    ...

@cache_page(60 * 15)
def post_list(request):
    ...
```

Decorators wrap views — order matters (bottom decorator runs first on the way in).
"""),
"errors": _views_block("Custom Error Handlers", """
```python
# urls.py (project level)
handler404 = "mysite.views.page_not_found"
handler500 = "mysite.views.server_error"
```

```python
# views.py
def page_not_found(request, exception):
    return render(request, "404.html", status=404)
```

With `DEBUG=True`, you see debug pages instead of custom handlers.
"""),
}

# Map chapter number -> topic dict + topic order
CH4.update(CH4_EXTRA)

CHAPTER_TOPICS = {
    2: (CH2, list(CH2.keys())),
    3: (CH3, list(CH3.keys())),
    4: (CH4, list(CH4.keys())),
}

try:
    from django_topics_ch5_14 import CHAPTER_TOPICS_EXTRA
    CHAPTER_TOPICS.update(CHAPTER_TOPICS_EXTRA)
except ImportError:
    pass
