"""Per-chapter metadata for TypeScript chapter expansion."""

# Each entry: filename, order, fm_title, description, tags, h1, welcome, toc, best, mistakes, interviews, exercises, summary, prev, next, extra_sections

def ch02():
    return dict(
        filename="ch02-types-and-primitives.md",
        order=2,
        title="Chapter 2 — Types and Primitives",
        desc="Primitive types, arrays, tuples, any, unknown, void, never, and type annotations in TypeScript.",
        tags=["typescript", "types", "primitives", "any", "unknown"],
        h1="Chapter 2: Types and Primitives",
        welcome="Every value in TypeScript has a type. This chapter builds your foundation — primitives, arrays, tuples, unions, and the special types `any`, `unknown`, `void`, and `never`.",
        toc=[
            "The Type System at a Glance", "Primitive Types", "string, number, boolean",
            "null and undefined", "Type Annotations vs Inference", "Arrays",
            "Tuples", "The object Type", "Union Types", "any — Escape Hatch",
            "unknown — Type-Safe Top Type", "void", "never", "Literal Types",
            "Type Aliases for Primitives", "Summary Table", "Best Practices",
            "Common Mistakes", "Interview Points", "Exercises", "Chapter Summary",
        ],
        best=[
            "Prefer inference for obvious literals; annotate function parameters.",
            "Use `unknown` instead of `any` for external data.",
            "Enable `strictNullChecks` and model null with unions.",
            "Use `readonly` arrays when data must not mutate.",
            "Use literal unions instead of `string` for fixed sets of values.",
        ],
        mistakes=[
            ("Using `any` everywhere", "`let x: any = getData()`", "Use `unknown` and narrow, or define a proper interface."),
            ("Ignoring `undefined` in optional props", "`user.email.toLowerCase()` when `email?`", "Use optional chaining: `user.email?.toLowerCase()`."),
            ("Confusing `void` with `undefined` only", "Thinking `void` means no return at runtime", "`void` means ignore return value; callers may still get `undefined`."),
            ("Tuple vs array confusion", "`let t: number[] = [1, 'two']`", "Use tuples `[number, string]` when positions have different types."),
            ("Widening literal types accidentally", "`let d = 'north'; d = 'east'` then assigning invalid direction", "Annotate `let d: Direction = 'north'` or use `as const`."),
        ],
        interviews=[
            ("Difference between `any` and `unknown`?", "`any` disables checking; `unknown` requires narrowing before use."),
            ("What is `never` used for?", "Functions that never return, and exhaustiveness checking in switches."),
            ("What is a union type?", "A value that can be one of several types: `string | number`."),
            ("What is `void`?", "Absence of a useful return value; typically functions that only side-effect."),
            ("What is type inference?", "Compiler deduces types from initializers and context."),
        ],
        exercises=[
            ("Primitive annotations", "Declare username, score, premium flag with correct types.", "Use `string`, `number`, `boolean`."),
            ("Readonly tuple", "Create `readonly [string, number]` for product name and price.", "Tuple syntax with `readonly`."),
            ("unknown pipeline", "Write `parseJson(s: string): unknown` and safely read a `name` property.", "Use `typeof` and `in` checks."),
            ("never exhaustiveness", "Add a case to a `Theme` union and fix the `never` error in `default`.", "Chapter 2 `never` section pattern."),
            ("Union formatter", "Function accepting `string | number` returning string representation.", "Use `typeof` narrowing."),
            ("null safety", "Model optional phone with `string | undefined` and formatter returning `N/A`.", "Strict null checks."),
        ],
        summary=[
            "Primitives: `string`, `number`, `boolean`, `bigint`, `symbol`, `null`, `undefined`.",
            "Prefer `unknown` over `any`; understand `void` and `never`.",
            "Arrays use `T[]` or `Array<T>`; tuples fix length and per-index types.",
            "Unions express multiple possibilities; narrow before use (Chapter 8).",
        ],
        prev=("ch01-introduction.md", "Introduction to TypeScript"),
        nxt=("ch03-interfaces-and-type-aliases.md", "Interfaces and Type Aliases"),
        extra=[
            ("Why JavaScript typeof lies about null", "`typeof null === 'object'` is a famous JS bug. TypeScript's type system treats `null` separately when `strictNullChecks` is on.",),
            ("Number is one type", "Unlike some languages, TS has no separate `int` / `float` — all are `number` (IEEE 754).",),
            ("When to use bigint", "Use `bigint` when integers exceed `Number.MAX_SAFE_INTEGER` (2^53 - 1).",),
            ("Readonly vs const", "`const x = []` prevents rebinding; `readonly` prevents `push` on the array type.",),
            ("Optional chaining preview", "`obj?.prop` short-circuits on `null`/`undefined` — essential with strict nulls.",),
        ],
    )


def ch03():
    return dict(
        filename="ch03-interfaces-and-type-aliases.md",
        order=3,
        title="Chapter 3 — Interfaces and Type Aliases",
        desc="Object shapes with interfaces and type aliases, extends, intersection, and when to use each.",
        tags=["typescript", "interfaces", "types", "extends", "intersection"],
        h1="Chapter 3: Interfaces and Type Aliases",
        welcome="Real apps model users, products, and API payloads. This chapter teaches how to describe object shapes with interfaces and type aliases, compose them, and understand structural typing.",
        toc=[
            "Describing Object Shapes", "Interfaces", "Optional and Readonly",
            "Index Signatures", "Type Aliases for Objects", "Interface vs Type Alias",
            "Extending Interfaces", "Intersection Types", "Structural Typing",
            "Excess Property Checking", "Declaration Merging", "API Models",
            "Best Practices", "Common Mistakes", "Interview Points", "Exercises", "Chapter Summary",
        ],
        best=[
            "Use `interface` for public object contracts; `type` for unions and utilities.",
            "Centralize shared models in `types/` or `models/`.",
            "Mark only truly optional fields with `?`.",
            "Prefer composition (`extends` / `&`) over copy-paste fields.",
        ],
        mistakes=[
            ("Duplicating shapes", "Copying the same fields in ten interfaces", "Extract `BaseEntity` and extend."),
            ("interface for unions", "`interface Status = 'a' | 'b'`", "Use `type Status = 'a' | 'b'`."),
            ("any in index signatures", "`[key: string]: any`", "Use `unknown` or a specific value type."),
            ("Fighting excess property checks", "Random extra keys on inline literals", "Assign to a variable first or fix the target type."),
        ],
        interviews=[
            ("interface vs type?", "Both describe shapes; `interface` can merge and extends cleanly; `type` supports unions and advanced types."),
            ("What is structural typing?", "Types match by shape, not by name — duck typing at compile time."),
            ("What is excess property checking?", "Inline object literals cannot have unknown properties when assigned to a type."),
            ("extends vs intersection?", "Similar for objects; conflicts in `&` can become `never` on a property."),
        ],
        exercises=[
            ("E-commerce Product", "Define `Product` and extend to `DigitalProduct`.", "Use `extends`."),
            ("Soft delete entity", "Combine `HasTimestamps` and `HasSoftDelete` with `&`.", "Intersection types."),
            ("Structural typing", "Pass extra property via variable vs inline literal.", "See excess property error."),
            ("ApiResult union", "Model success and failure variants.", "Preview Chapter 8."),
            ("Pick preview", "Create `ProductSummary` with Pick.", "Chapter 6 utilities."),
            ("Readonly API model", "Make `createdAt` readonly on an interface.", "readonly modifier."),
        ],
        summary=[
            "Interfaces and type aliases document object contracts.",
            "Extend or intersect to compose; structural typing matches by shape.",
            "Optional `?`, `readonly`, and index signatures model real APIs.",
        ],
        prev=("ch02-types-and-primitives.md", "Types and Primitives"),
        nxt=("ch04-functions.md", "Functions"),
        extra=[
            ("Callable interfaces", "Interfaces can describe functions: `(x: number) => void`.",),
            ("Extending multiple interfaces", "`interface A extends B, C` inherits all members.",),
        ],
    )


# Shorter config factory for remaining chapters
def _cfg(
    num, fname, title, desc, tags, h1, welcome, toc, best, mistakes, interviews, exercises, summary, prev, nxt, extra=None
):
    return dict(
        filename=fname, order=num, title=title, desc=desc, tags=tags,
        h1=h1,
        welcome=welcome, toc=toc, best=best, mistakes=mistakes,
        interviews=interviews, exercises=exercises, summary=summary,
        prev=prev, nxt=nxt, extra=extra or [],
    )


CHAPTER_CONFIGS = [
    ch02(),
    ch03(),
    _cfg(4, "ch04-functions.md", "Chapter 4 — Functions",
         "Function types, optional/default/rest params, overloads, and higher-order functions.",
         ["typescript", "functions", "overloads", "parameters"],
         "Chapter 4: Functions",
         "Functions are the heart of TypeScript programs. This chapter covers typing parameters, return types, overloads, `this`, and async functions.",
         ["Function Type Syntax", "Optional Parameters", "Default Parameters", "Rest Parameters",
          "Return Types", "Function Overloads", "Generic Functions Preview", "Higher-Order Functions",
          "this Typing", "Async Functions", "Best Practices", "Common Mistakes", "Interview Points", "Exercises", "Chapter Summary"],
         ["Annotate parameters; let return types be inferred only when obvious internally.",
          "Use overloads sparingly for call-signature differences.",
          "Prefer rest params over `arguments` object."],
         [("Optional before required", "`function f(a?: number, b: string)`", "Put required parameters first."),
          ("Wrong overload implementation", "Implementation signature not compatible with overloads", "Ensure impl accepts all overload cases."),
          ("Using `Function` type", "`let fn: Function`", "Use specific function types or generics.")],
         [("What are function overloads?", "Multiple call signatures, one implementation."),
          ("Covariance/contrariance basics?", "Parameters are checked contravariantly under strictFunctionTypes.")],
         [("Overload pair", "Write overloads for `format(value: number): string` and `format(value: boolean): string`.", "One implementation."),
          ("Rest sum", "Typed rest parameters summing numbers.", "Use `...nums: number[]`."),
          ("HOF filter", "Type `filterItems<T>` with predicate.", "Generics in Chapter 5."),
          ("Async fetch", "Type `loadUser(id: string): Promise<User>`.", "Promise generic."),
          ("this in method", "Class method vs arrow property for callbacks.", "Chapter 7."),
          ("Explicit return", "Export function with explicit return type.", "Public API clarity.")],
         ["Optional/default/rest parameters; overloads; async `Promise<T>`.", "Strict function types affect callback assignability."],
         ("ch03-interfaces-and-type-aliases.md", "Interfaces and Type Aliases"),
         ("ch05-generics.md", "Generics"),
         [("Inferring callback parameters", "Contextual typing infers parameter types in `arr.map(x => x * 2)`.",)]),
    _cfg(5, "ch05-generics.md", "Chapter 5 — Generics",
         "Generic functions, classes, constraints, defaults, and reusable patterns.",
         ["typescript", "generics", "constraints", "patterns"],
         "Chapter 5: Generics",
         "Generics let you write reusable code without losing type information. This chapter covers functions, classes, constraints, and common patterns.",
         ["Why Generics", "Generic Functions", "Generic Interfaces", "Generic Classes",
          "Constraints with extends", "keyof and getProperty", "Default Type Parameters",
          "Generic Utilities Preview", "Variance Note", "Best Practices", "Common Mistakes", "Interview Points", "Exercises", "Chapter Summary"],
         ["Name type parameters meaningfully: `T` ok for one param; use `TItem` in complex APIs.",
          "Use constraints instead of `any` inside generics."],
         [("Too many type params", "`function f<T, U, V, W>`", "Simplify or use an options object type."),
          ("Constraint too loose", "`T extends object`", "Use `extends HasId` or specific interface.")],
         [("What is a generic?", "Type parameter placeholder resolved at call site."),
          ("What is `extends` in generics?", "Constraint — T must satisfy a shape.")],
         [("identity<T>", "Implement generic identity function.", "Simplest generic."),
          ("getProperty", "Use `keyof T` safe property access.", "Constraint pattern."),
          ("Stack class", "Generic `Stack<T>` with push/pop.", "Generic class."),
          ("Default generic", "ApiResponse with default `T = unknown`.", "Default type param."),
          ("Memoize", "Typed memoize for unary functions.", "Higher-order generic."),
          ("Constraint merge", "T extends A & B.", "Intersection constraint.")],
         ["Generics preserve type information across reuse.", "Constraints limit type parameters safely."],
         ("ch04-functions.md", "Functions"), ("ch06-utility-types.md", "Utility Types"), []),
    _cfg(6, "ch06-utility-types.md", "Chapter 6 — Utility Types",
         "Partial, Required, Readonly, Pick, Omit, Record, ReturnType, Parameters, Awaited, and more.",
         ["typescript", "utility-types", "Partial", "Pick", "Omit"],
         "Chapter 6: Utility Types",
         "TypeScript ships powerful built-in type transformers. This chapter shows how to derive new types from existing ones — essential for forms, APIs, and DTOs.",
         ["What Are Utility Types", "Partial", "Required", "Readonly", "Pick", "Omit",
          "Record", "Exclude and Extract", "NonNullable", "ReturnType", "Parameters",
          "Awaited", "Composition Patterns", "Custom Utilities", "Best Practices", "Interview Points", "Exercises", "Chapter Summary"],
         ["Compose utilities: `Partial<Pick<User,'name'>>` for patch DTOs.",
          "Prefer utilities over manual duplicate interfaces."],
         [("Over-using Pick/Omit", "Pick 1 field from huge type repeatedly", "Consider domain-specific DTO types."),
          ("Record with any values", "`Record<string, any>`", "Narrow value type.")],
         [("What does Partial do?", "Makes all properties optional."),
          ("ReturnType use case?", "Extract function return type for wrappers.")],
         [("Update DTO", "Build `UserUpdate` with Partial and Omit id.", "Composition."),
          ("Role map", "Record<Role, Permission[]>.", "Record utility."),
          ("Unwrap promise", "Use Awaited on nested Promise.", "Async types."),
          ("Pick preview card", "ProductSummary with Pick.", "3 fields only."),
          ("Custom Optional", "Map properties to optional via mapped type.", "Advanced."),
          ("ReturnType wrapper", "Log wrapper preserving return type.", "ReturnType<>")],
         ["Utility types transform existing types without duplication.", "Essential for CRUD and API layers."],
         ("ch05-generics.md", "Generics"), ("ch07-classes-and-oop.md", "Classes and OOP"), []),
    _cfg(7, "ch07-classes-and-oop.md", "Chapter 7 — Classes and OOP",
         "Classes, access modifiers, readonly, static, abstract classes, and implements.",
         ["typescript", "classes", "oop", "abstract", "implements"],
         "Chapter 7: Classes and OOP",
         "TypeScript adds types to JavaScript classes — modifiers, abstract members, and interfaces implemented by classes.",
         ["Class Basics", "Parameter Properties", "Access Modifiers", "readonly",
          "static Members", "Inheritance", "override", "Abstract Classes",
          "implements", "Getters and Setters", "Best Practices", "Interview Points", "Exercises", "Chapter Summary"],
         ["Prefer composition over deep inheritance trees.",
          "Use `implements` to document contracts; classes for behavior with state."],
         [("public everything", "All fields public by default habit", "Mark internal state `private`."),
          ("Arrow vs method in React", "Wrong `this` in class components", "Use arrow fields or bind in constructor.")],
         [("abstract vs interface?", "abstract can have implementation; interface is shape only."),
          ("private vs #?", "private is compile-time; # is runtime private field.")],
         [("User class", "Class with constructor and method.", "Basics."),
          ("Abstract repo", "Abstract Repository<T> with save/find.", "Abstract pattern."),
          ("implements", "Logger implements interface.", "Contract."),
          ("override", "Subclass override with keyword.", "TS 4.3+."),
          ("static util", "MathUtils static methods.", "static keyword."),
          ("Generic Queue", "Queue<T> class.", "Generic class.")],
         ["Classes type OOP in TS; modifiers control visibility.", "Abstract classes template shared behavior."],
         ("ch06-utility-types.md", "Utility Types"), ("ch08-type-narrowing.md", "Type Narrowing"), []),
    _cfg(8, "ch08-type-narrowing.md", "Chapter 8 — Type Narrowing",
         "typeof, instanceof, in, equality, discriminated unions, and type predicates.",
         ["typescript", "narrowing", "type-guards", "discriminated-unions"],
         "Chapter 8: Type Narrowing",
         "Unions are only useful if you can safely narrow them. This chapter teaches control-flow analysis and user-defined type guards.",
         ["Why Narrowing", "typeof guards", "Truthiness", "Equality Narrowing",
          "instanceof", "in Operator", "Discriminated Unions", "Type Predicates",
          "asserts", "assertNever", "Best Practices", "Interview Points", "Exercises", "Chapter Summary"],
         ["Use discriminated unions with a literal `kind` or `type` field.",
          "Avoid single boolean flags for complex state — use unions."],
         [("Cast instead of narrow", "`as User` without checks", "Validate then narrow."),
          ("Forgotten default in switch", "Missing case when union grows", "Use `never` exhaustiveness.")],
         [("What is a type predicate?", "`function isUser(x): x is User`."),
          ("Discriminated union?", "Union members share a discriminant literal field.")],
         [("typeof pad", "Pad string or number.", "typeof branches."),
          ("ApiResult", "Handle success vs failure branches.", "Discriminated union."),
          ("isUser guard", "User-defined type guard.", "predicate syntax."),
          ("assertNever", "Add case and fix exhaustiveness.", "never type."),
          ("filter predicate", "Array filter with type predicate.", "T[] narrow."),
          ("in operator", "Fish vs Bird with in.", "Property check.")],
         ["Narrowing refines types within control flow.", "Discriminated unions scale best."],
         ("ch07-classes-and-oop.md", "Classes and OOP"), ("ch09-enums-and-literals.md", "Enums and Literals"), []),
    _cfg(9, "ch09-enums-and-literals.md", "Chapter 9 — Enums and Literal Types",
         "Numeric/string/const enums, literal types, as const, and modern alternatives.",
         ["typescript", "enums", "literals", "as-const"],
         "Chapter 9: Enums and Literal Types",
         "Literal types and const assertions are often preferable to enums. This chapter compares all approaches.",
         ["Literal Types", "Union of Literals", "Numeric Enums", "String Enums",
          "const enum", "as const", "const Object Pattern", "satisfies",
          "Template Literal Types", "Best Practices", "Interview Points", "Exercises", "Chapter Summary"],
         ["Prefer `as const` objects or union literals over numeric enums.",
          "Use string enums when you need runtime object iteration."],
         [("Numeric enum surprises", "Reverse mapping and unexpected numbers", "Prefer string unions."),
          ("const enum pitfalls", "Inlining issues across projects", "Often use plain union instead.")],
         [("enum vs union?", "Unions have no runtime cost; enums emit JS object."),
          ("What does as const do?", "Makes values deeply readonly literals.")],
         [("Theme union", "Type Theme and switch.", "Literal union."),
          ("Routes as const", "Route map with satisfies.", "satisfies operator."),
          ("String enum", "OrderStatus string enum.", "Compare to union."),
          ("HttpStatus", "Union of status codes.", "Literal numbers."),
          ("Template literal", "Event handler name type.", "Template literal types."),
          ("Migrate enum", "Replace numeric enum with const object.", "Modern pattern.")],
         ["Literal unions are lightweight; enums have runtime representation.", "as const + satisfies are modern defaults."],
         ("ch08-type-narrowing.md", "Type Narrowing"), ("ch10-modules-and-config.md", "Modules and Config"), []),
    _cfg(10, "ch10-modules-and-config.md", "Chapter 10 — Modules and Config",
         "ES modules, imports/exports, path aliases, tsconfig.json, and project references.",
         ["typescript", "modules", "tsconfig", "imports"],
         "Chapter 10: Modules and Config",
         "Modules organize code; tsconfig controls the compiler. This chapter connects both for real projects.",
         ["ES Modules", "Named and Default Exports", "import type", "Path Aliases",
          "Barrel Files", "tsconfig Structure", "strict Options", "Project References",
          "Ambient Declarations", "package.json types", "Vite + TS", "Best Practices", "Interview Points", "Exercises", "Chapter Summary"],
         ["Use `import type` for type-only imports (erased, helps bundlers).",
          "One tsconfig per package in monorepos; use project references."],
         [("Barrel file cycles", "index.ts re-exports causing circular imports", "Import from concrete modules."),
          ("Wrong moduleResolution", "Cannot find module in Node ESM", "Set NodeNext or bundler per tool.")],
         [("What is moduleResolution?", "How TS resolves import paths."),
          ("import type vs import?", "type-only imports elided from JS emit.")],
         [("Split modules", "Move utils to separate file and import.", "named exports."),
          ("Path alias", "Configure @/* paths.", "paths in tsconfig."),
          ("declare module", "Ambient module for .css imports.", "shims."),
          ("strict flags", "Document 5 strict flags in tsconfig.", "strict family."),
          ("type-only import", "Refactor to import type.", "isolatedModules friendly."),
          ("Vite config", "Align moduleResolution bundler.", "Chapter tooling.")],
         ["ES modules are standard; tsconfig must match your runtime/bundler.", "Path aliases improve imports."],
         ("ch09-enums-and-literals.md", "Enums and Literals"), ("ch11-async-typescript.md", "Async TypeScript"), []),
    _cfg(11, "ch11-async-typescript.md", "Chapter 11 — Async TypeScript",
         "Promises, async/await, error typing, fetch, and concurrency utilities.",
         ["typescript", "async", "promises", "await", "fetch"],
         "Chapter 11: Async TypeScript",
         "Async code is everywhere. This chapter types Promises, results, errors, and concurrent patterns safely.",
         ["Promise<T>", "async Functions", "Awaited", "Typing fetch",
          "Error Types", "Result Union", "Promise.all", "Async Generators",
          "void in callbacks", "AbortController", "Best Practices", "Interview Points", "Exercises", "Chapter Summary"],
         ["Type the success path and model errors explicitly.",
          "Validate JSON at boundaries — types do not exist at runtime."],
         [("Promise<any>", "Untyped fetch json()", "Use unknown + parser or schema."),
          ("Swallowing errors", "empty catch blocks", "Log or return Result type.")],
         [("Awaited utility?", "Unwraps Promise nested in types."),
          ("Promise.all typing?", "Tuple of promises becomes tuple of results.")],
         [("delay helper", "Promise<void> delay ms.", "Simple Promise."),
          ("Result type", "Success | Failure union.", "Discriminated union."),
          ("fetchUser", "Typed JSON parse with guards.", "unknown pipeline."),
          ("Promise.all", "Parallel fetches typed.", "tuple inference."),
          ("HttpError class", "Custom error with status.", "instanceof narrow."),
          ("Abort timeout", "AbortController with fetch.", "optional advanced.")],
         ["Async functions return Promise<T>; use Awaited for nested promises.", "Validate external JSON."],
         ("ch10-modules-and-config.md", "Modules and Config"), ("ch12-react-with-typescript.md", "React with TypeScript"), []),
    _cfg(12, "ch12-react-with-typescript.md", "Chapter 12 — React with TypeScript",
         "Component props, children, events, hooks, refs, context, and generic components.",
         ["typescript", "react", "hooks", "components", "jsx"],
         "Chapter 12: React with TypeScript",
         "React and TypeScript together catch UI bugs early. This chapter types props, events, hooks, and advanced component patterns.",
         ["Why TS + React", "Component Props", "children", "Events",
          "useState", "useReducer", "useRef", "Context", "Generic Lists",
          "forwardRef", "ComponentProps", "Best Practices", "Interview Points", "Exercises", "Chapter Summary"],
         ["Define props interfaces; export when reused.",
          "Use `ComponentPropsWithoutRef` to extend native elements."],
         [("React.FC everywhere", "Implicit children issues", "Prefer explicit props interface."),
          ("any for event handlers", "`onChange={(e: any) =>`", "Use `ChangeEvent<HTMLInputElement>`.")],
         [("How to type useState?", "Pass initial value or generic: `useState<User | null>(null)`."),
          ("children type?", "ReactNode for flexible children.")],
         [("Button props", "Extend button with variant prop.", "HTML attributes."),
          ("Controlled input", "Typed onChange handler.", "events."),
          ("useReducer", "Discriminated action union.", "redux-style."),
          ("Context hook", "Typed context + custom hook.", "null guard."),
          ("Generic List", "List<T> render prop.", "generics in UI."),
          ("forwardRef input", "Ref to input element.", "forwardRef types.")],
         ["Props interfaces, typed events, and hooks prevent UI regressions.", "Generics power reusable list/table components."],
         ("ch11-async-typescript.md", "Async TypeScript"), ("ch13-best-practices.md", "Best Practices"), []),
    _cfg(13, "ch13-best-practices.md", "Chapter 13 — Best Practices",
         "Strict mode, naming, avoiding any, branded types, and team conventions.",
         ["typescript", "best-practices", "strict", "conventions"],
         "Chapter 13: Best Practices",
         "Writing TypeScript is easy; writing *maintainable* TypeScript requires discipline. This chapter collects professional conventions.",
         ["Enable strict", "Compiler Flags Table", "Boundary Validation",
          "unknown over any", "interface vs type", "Discriminated Unions",
          "Branded Types", "Avoid Assertion Abuse", "DTO Patterns", "ESLint",
          "Documentation", "Code Review Checklist", "Interview Points", "Exercises", "Chapter Summary"],
         ["Treat types as documentation; validate at boundaries.",
          "Enable extra strict flags incrementally on mature codebases."],
         [("Type assertion spam", "`as any` to silence errors", "Fix types or use type guards."),
          ("Leaking any", "One any poisons inference", "Ban explicit any in lint rules.")],
         [("strictNullChecks?", "null/undefined not assignable unless in union."),
          ("Branded type?", "Nominal-like tag via intersection with unique symbol.")],
         [("strict tsconfig", "Enable 3 additional strict flags.", "incremental adoption."),
          ("Branded UserId", "Prevent mixing id types.", "branding pattern."),
          ("ESLint rule", "Add no-explicit-any.", "tooling."),
          ("DTO update", "Partial<Omit<User,'id'>>.", "utilities."),
          ("Review checklist", "Write 10-item PR checklist.", "team process."),
          ("JSDoc export", "Document exported function.", "IDE help.")],
         ["Strict mode + lint + reviews keep codebases healthy.", "Types complement runtime validation."],
         ("ch12-react-with-typescript.md", "React with TypeScript"), ("ch14-interview-prep.md", "Interview Preparation"), []),
    _cfg(14, "ch14-interview-prep.md", "Chapter 14 — Interview Preparation",
         "Common TypeScript interview questions, whiteboard challenges, and study strategies.",
         ["typescript", "interview", "qa"],
         "Chapter 14: Interview Preparation",
         "This capstone chapter consolidates interview topics across the course with sample answers and practice challenges.",
         ["How to Use This Chapter", "Core Concepts Q&A", "Generics and Utilities Q&A",
          "Narrowing and Unions Q&A", "Tooling Q&A", "React TS Q&A",
          "Whiteboard Challenges", "Behavioral Tips", "Study Plan", "Interview Points", "Exercises", "Chapter Summary"],
         ["Explain trade-offs, not buzzwords.", "Link answers to bugs prevented in real projects."],
         [("Memorizing only syntax", "Cannot explain why unknown > any", "Study rationale and examples."),
          ("Ignoring JavaScript fundamentals", "Cannot explain event loop but knows Pick<Omit>", "Balance TS with JS depth.")],
         [("Most common TS question?", "Often: difference any vs unknown, or what is generics."),
          ("How to answer system design with TS?", "Mention API contracts, shared types, validation at boundaries.")],
         [("Flashcards", "Write 20 flashcards from this chapter.", "spaced repetition."),
          ("Mock interview", "Pair practice 45 minutes.", "explain aloud."),
          ("Whiteboard deepPartial", "Sketch recursive Partial type.", "advanced."),
          ("Implement get", "Type-safe API client sketch.", "generics + unknown."),
          ("Narrowing live", "Given union code, narrate narrowing steps.", "Chapter 8."),
          ("strict flags", "List strict family and one benefit each.", "Chapter 10/13.")],
         ["Interviewers test inference, unions, generics, narrowing, and pragmatic strictness.", "Practice explaining out loud."],
         ("ch13-best-practices.md", "Best Practices"), None, []),
]
